#!/bin/bash -eu
set -o pipefail

logPrefix="$(basename "$0")"
log() {
  echo "[$logPrefix] $*"
}

log "WARNING: sudo is required to check size of postgres docker volume."

# Check available space in the docker root dir.  This is less risky than with /volumes appended
# as on some systems the docker root dir may not be executable by the current user.
free="$(df --output=avail "$(docker info --format '{{print .DockerRootDir}}')" | tail -n+2)"

containerName="central_postgres_1"
volume="$(docker inspect --format='{{(index .Mounts 0).Name}}' "$containerName")"
if [[ "$volume" = "" ]]; then
  log "!!!"
  log "!!! Volume not found for container: $containerName !!!"
  log "!!!"
  log "!!! Cannot continue !!!"
  log "!!!"
  exit 1
fi
mountpoint="$(docker volume inspect --format='{{.Mountpoint}}' "$volume")"
used="$(sudo du -s "$mountpoint" | cut -f1)"

log
log "    Free space: $(numfmt --to=si "$((free*1000))")B"
log "Required space: $(numfmt --to=si "$((used*1000))")B"
log

if [[ "$used" -lt "$free" ]]; then
  log "It looks like you have enough space to upgrade :¬)"
  log
  log "Please follow instructions at https://docs.getodk.org/central-upgrade/"
  log
else
  log "!!!"
  log "!!! ERROR: You may not have enough space available to upgrade!"
  log "!!!"
  log "!!! Increase your disk by at least $(numfmt --to=si -- "$(((used-free)*1000))")B and try again."
  log "!!!"
  log
  exit 1
fi
