#!/bin/bash -eu
set -o pipefail

logPrefix="$(basename "$0")"
log() {
  echo "[$logPrefix] $*"
}

free="$(df --output=avail . | tail -n+2)"
used="$(sudo du -s $(docker volume inspect --format='{{.Mountpoint}}' $(docker inspect --format='{{(index .Mounts 0).Name}}' central_postgres_1)) | cut -f1)"

log
log "    Free space: $(numfmt --to=si "$((free*1000))")B"
log "Required space: $(numfmt --to=si "$((used*1000))")B"
log

if [[ "$used" -lt "$free" ]]; then
	log "It looks like you have enough space to upgrade :¬)"
	log
	log "Please follow instructions at https://docs.getodk.org/central-upgrade/"
	log
else
	log "!!!"
	log "!!! ERROR: You may not have enough space available to upgrade!"
	log "!!!"
	log "!!! Increase your disk by at least $(numfmt --to=si -- "$(((used-free)*1000))")B and try again."
	log "!!!"
	log
	exit 1
fi
