version: "3"
services:
  service:
    build:
      context: .
      dockerfile: service.dockerfile
    command: [ "pm2-runtime", "./pm2.config.js" ]
    restart: always
    logging:
      driver: json-file
