#!/bin/bash -eux
set -o pipefail

alreadyRunMarkerFile="$PGDATA/../.odk-postgres-9.6-to-14-migration-completed-ok"

echo "------------------------------XXX------------------------------"
ls -al "$PGDATA/.."
ls -al "$PGDATA"
echo "------------------------------XXX------------------------------"

logPrefix="$(basename $0)"
log() {
  echo "$(TZ=GMT date) [$logPrefix] $*"
}

log "Waiting for migration to complete..."
while ! [[ -f "$alreadyRunMarkerFile" ]]; do sleep 1; done
log "Migration complete."

log "Starting postgres..."
# call ENTRYPOINT + CMD from parent Docker image
docker-entrypoint.sh postgres
