#!/bin/bash -eux
set -o pipefail

alreadyRunMarkerFile=/var/lib/postgresql/14/data/odk-9.6-to-14-migration-completed-ok

logPrefix="$(basename $0)"
log() {
  echo "$(TZ=GMT date) [$logPrefix] $*"
}

log "Checking for existing migration marker file..."
if [[ -f "$alreadyRunMarkerFile" ]]; then
  log "Migration has been run previously."
else
  if [[ -f /var/lib/postgresql/data/PG_VERSION ]]; then
    log "Migration not run previously; migrating now..."

    # --link should take less disk space, but doesn't work on MacOSX on github actions
    # TODO work out why and if there is a better way to approach this
    docker-upgrade pg_upgrade --link || docker-upgrade pg_upgrade

    # see https://github.com/tianon/docker-postgres-upgrade/issues/16,
    #     https://github.com/tianon/docker-postgres-upgrade/issues/1
    cp "$PGDATAOLD/pg_hba.conf" "$PGDATANEW/pg_hba.conf"

    log "Starting postgres server for maintenance..."
    gosu postgres pg_ctl -D /var/lib/postgresql/14/data -l logfile start

    # As recommended by pg_upgrade:
    log "Updating extensions..."
    psql -f update_extensions.sql

    # As recommended by pg_upgrade:
    log "Regenerating optimizer statistics..."
    /usr/lib/postgresql/14/bin/vacuumdb --all --analyze-in-stages

    # As recommended by pg_upgrade:
    # TODO we need to document clearly that this is going to happen!
    log "Deleting old data files..."
    ./delete_old_cluster.sh

    log "Migration complete."
  else
    log "No legacy data found."
  fi
  touch "$alreadyRunMarkerFile"
fi

log "Shutting down."
