#!/bin/bash -eu
set -o pipefail

alreadyRunMarkerFile=9.6-to-14-migration-completed-ok

logPrefix="$(basename $0)"
log() {
	echo "[$logPrefix] $*"
}

#log "Checking for legacy data..."
#if [[ -d /var/lib/postgresql/data ]]; then
#  log "Legacy data directory found, moving to new location..."
#	mv /var/lib/postgresql/data /var/lib/postgresql/9.6/
#else
#	log "No legacy data found."
#fi

log "Checking for existing migration marker file..."
if [[ -f "$alreadyRunMarkerFile" ]]; then # TODO is there a more reliable way to test this?
	log "Migration has been run previously."
else
	if [[ -f /var/lib/postgresql/data/postgresql ]]; then
		log "Migration not run previously; migrating now..."
		docker-upgrade pg_upgrade
		log "Migration complete."
		touch "$alreadyRunMarkerFile"
	else
		log "No legacy data found."
	fi
fi

log "Starting postgres..."
# Start as per official postgres docker image
# See: https://github.com/docker-library/postgres/blob/master/14/bullseye/Dockerfile
docker-entrypoint.sh postgres
